server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: bWFuZG9yaWFudGV4dHJlbWVseXNlY3VyZXQyMTEzJDEyMzQ1

springdoc:
  swagger-ui:
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: task-service
        url: /task-service/v3/api-docs
      - name: authenthication-service
        url: /authenthication-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
  api-docs:
    enabled: true