spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

server:
  port: 8761

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: false
    fetch-registry: false