spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

server:
  port: 8013

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-produces-media-type: application/json
  paths-to-match: /tasks/**

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: task-instance-${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/taskdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: task-instance-${random.uuid}
    prefer-ip-address: true