spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

server:
  port: 8010

jwt:
  secret: ${JWT_SECRET:bWFuZG9yaWFudGV4dHJlbWVseXNlY3VyZXQyMTEzJDEyMzQ1}
  expiration: 86400 # 24 hours in milliseconds

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-produces-media-type: application/json
  paths-to-match: /auth/**

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: auth-instance-${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: auth-instance-${random.uuid}
    prefer-ip-address: true